# Generated by Django 6.0.1 on 2026-02-16 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_people_phone_number_alter_people_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='address',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
