# Generated by Django 6.0.1 on 2026-02-18 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_people_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='age',
        ),
    ]
