# Generated by Django 6.0.1 on 2026-02-21 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_mother_delete_fathername'),
    ]

    operations = [
        migrations.CreateModel(
            name='father',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('age', models.IntegerField()),
                ('address', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
